{
 "title": "TodoBot Users Dashboard",
 "tags": [ "users" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество пользователей",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "todobot_users_total", "legendFormat": "Всего пользователей" },
    { "expr": "todobot_active_users", "legendFormat": "Активные пользователи" }
   ]
  },
  {
   "title": "Время обработки операций авторизации",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(todobot_request_duration_seconds_sum{handler=~\"login|logout\"}[5m]) / rate(todobot_request_duration_seconds_count{handler=~\"login|logout\"}[5m])",
     "legendFormat": "{{handler}} - {{method}}"
    }
   ]
  },
  {
   "title": "Частота ошибок авторизации",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(todobot_errors_total{type=~\"invalid_password|create_user_error|get_user_error|update_user_error|create_session_error|delete_session_error\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Время отправки сообщений и уведомлений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(todobot_request_duration_seconds_sum{handler=~\"send_message|send_notifications\"}[5m]) / rate(todobot_request_duration_seconds_count{handler=~\"send_message|send_notifications\"}[5m])",
     "legendFormat": "{{handler}} - {{method}}"
    }
   ]
  }
 ]
}